// apps/vue-example/src/App.vue
<template>
  <div class="wrapper">
    <div class="email-sender">
      <h1>Test tsmailer</h1>

      <!-- Multiple Email Inputs -->
      <h2>Recipient Emails</h2>
      <div v-for="(email, index) in toEmails" :key="index" class="email-input">
        <label>
          To Email {{ index + 1 }}:
          <input type="email" v-model="toEmails[index]" required />
        </label>
      </div>
      <button @click="handleAddEmail" class="add-email">Add Another Email</button>

      <!-- Other Inputs -->
      <div class="input-group">
        <label>
          From Name:
          <input type="text" v-model="fromName" required />
        </label>
      </div>

      <div class="input-group">
        <label>
          To Name:
          <input type="text" v-model="toName" required />
        </label>
      </div>

      <div class="input-group">
        <label>
          Your Message:
          <textarea v-model="yourMessage" required></textarea>
        </label>
      </div>

      <h2>API Configuration</h2>
      <div class="input-group">
        <label>
          API Key:
          <input type="text" v-model="apiKey" required />
        </label>
      </div>

      <div class="input-group">
        <label>
          Provider ID:
          <input type="text" v-model="providerId" required />
        </label>
      </div>

      <div class="input-group">
        <label>
          Template ID:
          <input type="text" v-model="templateId" required />
        </label>
      </div>

      <button @click="handleSendMail" :disabled="loading" class="send-button">
        <span v-if="loading">Sending...</span>
        <span v-else>Send Email</span>
      </button>


    </div>
    <!-- Display Response Data -->
    <div v-if="responseData" class="response-data">
      <h2>Email Status</h2>
      <pre>{{ JSON.stringify(responseData, null, 2) }}</pre>
    </div>
  </div>
</template>

<script lang="ts">
import { ref } from 'vue'
import tsmailer from '@repo/tsmailer'

export default {
  setup() {
    // State to manage input fields
    const toEmails = ref<string[]>(['']) // Array for multiple recipient emails
    const fromName = ref('tester')
    const toName = ref('testee')
    const yourMessage = ref('test')
    const apiKey = ref('YOUR_API_KEY')
    const providerId = ref('YOUR_PROVIDER_ID')
    const templateId = ref('YOUR_TEMPLATE_ID')

    // State to hold the response data and loading state
    const responseData = ref<any>(null)
    const loading = ref(false)

    // Handle the email sending logic
    const handleSendMail = async () => {
      loading.value = true // Set loading state to true
      const send = tsmailer.init({
        apiKey: apiKey.value,
        providerId: providerId.value,
        templateId: templateId.value,
      })

      try {
        const data = await send({
          to: toEmails.value.filter(email => email.trim() !== ''), // Filter out empty emails
          options: {
            fromName: fromName.value,
            toName: toName.value,
            yourMessage: yourMessage.value,
          },
        })

        // Update responseData with the result from the API
        responseData.value = data
      } catch (error) {
        console.error('Error sending email:', error)
        // Optionally handle error feedback here
      } finally {
        loading.value = false // Reset loading state
      }
    }

    // Function to handle adding a new email input field
    const handleAddEmail = () => {
      toEmails.value.push('')
    }

    return {
      toEmails,
      fromName,
      toName,
      yourMessage,
      apiKey,
      providerId,
      templateId,
      handleSendMail,
      handleAddEmail,
      responseData,
      loading, // Expose loading state to the template
    }
  },
}
</script>

<style scoped>
.wrapper {
  display: flex;
  align-items: center;
  justify-content: center;
}

.email-sender {
  max-width: 600px;
  margin: auto;
  padding: 20px;
  border: 1px solid #ddd;
  border-radius: 8px;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
}

.input-group {
  margin-bottom: 15px;
}

.email-input {
  margin-bottom: 10px;
}

.send-button {
  background-color: #007bff;
  color: white;
  padding: 10px 15px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}

.send-button:disabled {
  background-color: #ccc;
  cursor: not-allowed;
}

.add-email {
  margin-top: 10px;
}

.response-data {
  margin-top: 20px;
  background-color: #f9f9f9;
  padding: 15px;
  border-radius: 5px;
  border: 1px solid #ddd;
}
</style>

// apps/react-vite-example/src/App.tsx
import { useState, useCallback } from 'react'
import tsmailer from '@repo/tsmailer'

function App() {
  // State to manage input fields
  const [loading, setLoading] = useState(false)
  const [toEmails, setToEmails] = useState<string[]>([''])
  const [fromName, setFromName] = useState('tester')
  const [toName, setToName] = useState('testee')
  const [yourMessage, setYourMessage] = useState('testing!')
  const [apiKey, setApiKey] = useState('YOUR_API_KEY')
  const [providerId, setProviderId] = useState('YOUR_PROVIDER_ID')
  const [templateId, setTemplateId] = useState('YOUR_TEMPLATE_ID')

  // State to manage response data
  const [response, setResponse] = useState<string | null>(null)

  // Initialize tsmailer with predefined apiKey, providerId, and templateId
  const send = tsmailer.init({
    apiKey,
    providerId,
    templateId,
  })

  // Handle the email sending logic
  const handleSendMail = useCallback(() => {
    setLoading(true) // Set loading to true
    setResponse(null) // Reset response state
    send({
      to: toEmails.filter((email) => email.trim() !== ''), // Filter out empty emails
      options: {
        fromName,
        toName,
        yourMessage,
      },
    })
      .then((data) => {
        setResponse(JSON.stringify(data, null, 2)) // Store response data
      })
      .catch((error) => {
        console.error('Error sending email:', error)
        alert('Failed to send email.')
        setResponse(JSON.stringify(error, null, 2)) // Store error response
      })
      .finally(() => {
        setLoading(false) // Reset loading state after the operation
      })
  }, [send, toEmails, fromName, toName, yourMessage])

  // Function to handle adding a new email input field
  const handleAddEmail = () => {
    setToEmails([...toEmails, ''])
  }

  // Function to handle changing an email input field
  const handleEmailChange = (index: number, value: string) => {
    const newEmails = [...toEmails]
    newEmails[index] = value
    setToEmails(newEmails)
  }

  return (
    <div
      style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
      }}
    >
      <div style={{ padding: '20px', fontFamily: 'Arial, sans-serif' }}>
        <h1 style={{ color: '#333' }}>Test tsmailer</h1>

        {/* Multiple Email Inputs */}
        <h2 style={{ color: '#555' }}>Recipient Emails</h2>
        {toEmails.map((email, index) => (
          <div key={index} style={{ marginBottom: '10px' }}>
            <label>
              To Email {index + 1}:
              <input
                type="email"
                value={email}
                onChange={(e) => handleEmailChange(index, e.target.value)}
                required
                style={{
                  marginLeft: '10px',
                  padding: '5px',
                  borderRadius: '4px',
                }}
              />
            </label>
          </div>
        ))}
        <button
          onClick={handleAddEmail}
          style={{ marginBottom: '20px', padding: '10px', borderRadius: '4px' }}
        >
          Add Another Email
        </button>

        {/* Other Inputs */}
        <div style={{ marginBottom: '20px' }}>
          <label>
            From Name:
            <input
              type="text"
              value={fromName}
              onChange={(e) => setFromName(e.target.value)}
              required
              style={{
                marginLeft: '10px',
                padding: '5px',
                borderRadius: '4px',
              }}
            />
          </label>
        </div>

        <div style={{ marginBottom: '20px' }}>
          <label>
            To Name:
            <input
              type="text"
              value={toName}
              onChange={(e) => setToName(e.target.value)}
              required
              style={{
                marginLeft: '10px',
                padding: '5px',
                borderRadius: '4px',
              }}
            />
          </label>
        </div>

        <div style={{ marginBottom: '20px' }}>
          <label>
            Your Message:
            <textarea
              value={yourMessage}
              onChange={(e) => setYourMessage(e.target.value)}
              required
              style={{
                marginLeft: '10px',
                padding: '5px',
                borderRadius: '4px',
                width: '100%',
                height: '100px',
              }}
            />
          </label>
        </div>

        <h2 style={{ color: '#555' }}>API Configuration</h2>
        <div style={{ marginBottom: '20px' }}>
          <label>
            API Key:
            <input
              type="text"
              value={apiKey}
              onChange={(e) => setApiKey(e.target.value)}
              required
              style={{
                marginLeft: '10px',
                padding: '5px',
                borderRadius: '4px',
              }}
            />
          </label>
        </div>

        <div style={{ marginBottom: '20px' }}>
          <label>
            Provider ID:
            <input
              type="text"
              value={providerId}
              onChange={(e) => setProviderId(e.target.value)}
              required
              style={{
                marginLeft: '10px',
                padding: '5px',
                borderRadius: '4px',
              }}
            />
          </label>
        </div>

        <div style={{ marginBottom: '20px' }}>
          <label>
            Template ID:
            <input
              type="text"
              value={templateId}
              onChange={(e) => setTemplateId(e.target.value)}
              required
              style={{
                marginLeft: '10px',
                padding: '5px',
                borderRadius: '4px',
              }}
            />
          </label>
        </div>

        <button
          onClick={handleSendMail}
          disabled={loading} // Disable button while loading
          style={{
            padding: '10px',
            borderRadius: '4px',
            backgroundColor: loading ? '#ccc' : '#4CAF50',
            color: 'white',
            cursor: loading ? 'not-allowed' : 'pointer',
          }}
        >
          {loading ? 'Sending...' : 'Send Email'}
        </button>
      </div>
      {/* Response Section */}
      {response && (
        <div
          style={{
            marginTop: '20px',
            backgroundColor: '#f0f0f0',
            padding: '10px',
            borderRadius: '4px',
          }}
        >
          <h3 style={{ color: '#333' }}>Response:</h3>
          <pre style={{ whiteSpace: 'pre-wrap' }}>{response}</pre>
        </div>
      )}
    </div>
  )
}

export default App
